# https://aka.ms/yaml
variables:
  - group: Keys
trigger: 
   branches:
     include:
       - 18.2
pool:
  vmImage: vs2017-win2016
steps:
- checkout: self
  clean: true
  submodules: true
- powershell: |
   $repository="$(Build.Repository.Name)"
   if ($repository -like "*/lab"){
      Write-Host "Finding Version.."
      $version=(& $(System.DefaultWorkingDirectory)\Support\build\go.ps1)|Select-Object -Last 1
      Write-Verbose -Verbose "##vso[build.updatebuildnumber]$version"
      $publishNugetFeed="https://xpandnugetserver.azurewebsites.net/nuget"
   }
   elseif ($repository -like "*/eXpand"){
      $version="$(Build.BuildNumber)"
      $publishNugetFeed="https://api.nuget.org/v3/index.json"
   }
   else{
      throw $repository
   }
   Write-Host "Start build.."
   $sources=@("https://api.nuget.org/v3/index.json","https://xpandnugetserver.azurewebsites.net/nuget","$(DXApiFeed)")   
   & $(System.DefaultWorkingDirectory)\support\build\go.ps1 -packageSources $sources -configuration "Release" -msbuild "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\msbuild.exe" -taskList @("Release","PublishNuget") -nugetApiKey $(NuGetApiKey) -version $version -publishNugetFeed $publishNugetFeed -Repository $repository
   if ($LastExitCode){
      exit $LastExitCode
   }
   Get-ChildItem "$(System.DefaultWorkingDirectory)\Build\_Package\$Version" -Recurse |ForEach-Object{
      Copy-Item $_.FullName -Destination $(Build.artifactstagingdirectory)
   }
   Copy-Item $(System.DefaultWorkingDirectory)\Build\Installer\eXpandFramework-$version.exe -Destination $(Build.artifactstagingdirectory)
  failOnStderr: true
  displayName: Build
- powershell: | 
   $repository="$(Build.Repository.Name)"
   if ($repository -like "*/lab"){
      $version="$(Build.BuildNumber)"
      $nugetServerUri="https://xpandnugetserver.azurewebsites.net/"
      $installerBuildUri="https://dev.azure.com/eXpandDevOps/eXpandFramework/_build/results?buildId=$(Build.BuildId)&view=results"
      $msg="Installer lab build [$version]($installerBuildUri) includes commit {Commits} that relate to this task. Please test if it addresses the problem. If you use nuget add our [NugetServer]({$nugetServerUri}) as a nuget package source in VS"
      $msg
      Checkpoint-GithubIssue -GitHubApp eXpandFramework -Owner $(GithubUserName) -Organization eXpandFramework -Repository1 eXpand -Repository2 "lab" -Message $msg -Pass $(GithubPass) 
   }
  displayName: 'Checkpoint-GithubIssue'
  failOnStderr: true
  enabled: true
- task: PublishPipelineArtifact@0
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifactName: Xpand.v$(Build.BuildNumber)
    targetPath: $(Build.ArtifactStagingDirectory)




