# https://aka.ms/yaml
variables:
  - group: Keys
trigger: 
   branches:
     include:
       - 18.2
pool:
  vmImage: vs2017-win2016
steps:
- checkout: self
  clean: true
  submodules: true
- task: PowerShell@2
  displayName: Release
  inputs:
    targetType: filePath
    filePath: .\.github\Azure-Pipeline.ps1
    arguments: $(Build.Repository.Name) $(DXApiFeed) $(NuGetApiKey) $(build.artifactstagingdirectory) $(BetaFeed)
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Xpand.v$(Build.BuildNumber)'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'Xpand.v$(Build.BuildNumber)'




